/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserUserimage from './UserUserimage';

/**
 * The Product model module.
 * @module model/Product
 * @version 1.0.0
 */
class Product {
    /**
     * Constructs a new <code>Product</code>.
     * @alias module:model/Product
     * @param productname {String} 
     * @param productdesc {String} 
     * @param productimage {module:model/UserUserimage} 
     * @param productcategory {String} 
     * @param productunit {String} 
     */
    constructor(productname, productdesc, productimage, productcategory, productunit) { 
        
        Product.initialize(this, productname, productdesc, productimage, productcategory, productunit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productname, productdesc, productimage, productcategory, productunit) { 
        obj['productname'] = productname;
        obj['productdesc'] = productdesc;
        obj['productimage'] = productimage;
        obj['productcategory'] = productcategory;
        obj['productunit'] = productunit;
    }

    /**
     * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Product} obj Optional instance to populate.
     * @return {module:model/Product} The populated <code>Product</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Product();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('productname')) {
                obj['productname'] = ApiClient.convertToType(data['productname'], 'String');
            }
            if (data.hasOwnProperty('productdesc')) {
                obj['productdesc'] = ApiClient.convertToType(data['productdesc'], 'String');
            }
            if (data.hasOwnProperty('productimage')) {
                obj['productimage'] = UserUserimage.constructFromObject(data['productimage']);
            }
            if (data.hasOwnProperty('productcategory')) {
                obj['productcategory'] = ApiClient.convertToType(data['productcategory'], 'String');
            }
            if (data.hasOwnProperty('productunit')) {
                obj['productunit'] = ApiClient.convertToType(data['productunit'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Product.prototype['_id'] = undefined;

/**
 * @member {String} productname
 */
Product.prototype['productname'] = undefined;

/**
 * @member {String} productdesc
 */
Product.prototype['productdesc'] = undefined;

/**
 * @member {module:model/UserUserimage} productimage
 */
Product.prototype['productimage'] = undefined;

/**
 * @member {String} productcategory
 */
Product.prototype['productcategory'] = undefined;

/**
 * @member {String} productunit
 */
Product.prototype['productunit'] = undefined;






export default Product;

