/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Product from './Product';
import UserUserimage from './UserUserimage';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     * @param useremail {String} 
     * @param password {String} 
     * @param username {String} 
     * @param usercategory {String} 
     * @param userimage {module:model/UserUserimage} 
     * @param userproducts {Array.<module:model/Product>} 
     * @param userstatus {String} 
     * @param usertown {String} 
     * @param useraddress {String} 
     * @param usertax {String} 
     */
    constructor(useremail, password, username, usercategory, userimage, userproducts, userstatus, usertown, useraddress, usertax, usersubscriptions) { 
        
        User.initialize(this, useremail, password, username, usercategory, userimage, userproducts, userstatus, usertown, useraddress, usertax, usersubscriptions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, useremail, password, username, usercategory, userimage, userproducts, userstatus, usertown, useraddress, usertax, usersubscriptions) { 
        obj['useremail'] = useremail;
        obj['password'] = password;
        obj['username'] = username;
        obj['usercategory'] = usercategory;
        obj['userimage'] = userimage;
        obj['userproducts'] = userproducts;
        obj['userstatus'] = userstatus;
        obj['usertown'] = usertown;
        obj['useraddress'] = useraddress;
        obj['usertax'] = usertax;
        obj['usersubscriptions'] = usersubscriptions;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('useremail')) {
                obj['useremail'] = ApiClient.convertToType(data['useremail'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('usercategory')) {
                obj['usercategory'] = ApiClient.convertToType(data['usercategory'], 'String');
            }
            if (data.hasOwnProperty('userimage')) {
                obj['userimage'] = UserUserimage.constructFromObject(data['userimage']);
            }
            if (data.hasOwnProperty('userproducts')) {
                obj['userproducts'] = ApiClient.convertToType(data['userproducts'], [Product]);
            }
            if (data.hasOwnProperty('userstatus')) {
                obj['userstatus'] = ApiClient.convertToType(data['userstatus'], 'String');
            }
            if (data.hasOwnProperty('usertown')) {
                obj['usertown'] = ApiClient.convertToType(data['usertown'], 'String');
            }
            if (data.hasOwnProperty('useraddress')) {
                obj['useraddress'] = ApiClient.convertToType(data['useraddress'], 'String');
            }
            if (data.hasOwnProperty('usertax')) {
                obj['usertax'] = ApiClient.convertToType(data['usertax'], 'String');
            }
            if (data.hasOwnProperty('usersubscriptions')) {
                obj['usersubscriptions'] = ApiClient.convertToType(data['usersubscriptions'], [Object]);
            }
            if (data.hasOwnProperty('usersuppliers')) {
                obj['usersuppliers'] = ApiClient.convertToType(data['usersuppliers'], [User]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
User.prototype['_id'] = undefined;

/**
 * @member {String} useremail
 */
User.prototype['useremail'] = undefined;

/**
 * @member {String} password
 */
User.prototype['password'] = undefined;

/**
 * @member {String} username
 */
User.prototype['username'] = undefined;

/**
 * @member {String} usercategory
 */
User.prototype['usercategory'] = undefined;

/**
 * @member {module:model/UserUserimage} userimage
 */
User.prototype['userimage'] = undefined;

/**
 * @member {Array.<module:model/Product>} userproducts
 */
User.prototype['userproducts'] = undefined;

/**
 * @member {String} userstatus
 */
User.prototype['userstatus'] = undefined;

/**
 * @member {String} usertown
 */
User.prototype['usertown'] = undefined;

/**
 * @member {String} useraddress
 */
User.prototype['useraddress'] = undefined;

/**
 * @member {String} usertax
 */
User.prototype['usertax'] = undefined;

User.prototype['usersubscriptions'] = undefined;






export default User;

