/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instane = new TempApi.User();
      //expect(instance).to.be.a(TempApi.User);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

    it('should have the property useremail (base name: "useremail")', function() {
      // uncomment below and update the code to test the property useremail
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

    it('should have the property usercategory (base name: "usercategory")', function() {
      // uncomment below and update the code to test the property usercategory
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

    it('should have the property userimage (base name: "userimage")', function() {
      // uncomment below and update the code to test the property userimage
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

    it('should have the property userproducts (base name: "userproducts")', function() {
      // uncomment below and update the code to test the property userproducts
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

    it('should have the property userstatus (base name: "userstatus")', function() {
      // uncomment below and update the code to test the property userstatus
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

    it('should have the property usertown (base name: "usertown")', function() {
      // uncomment below and update the code to test the property usertown
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

    it('should have the property useraddress (base name: "useraddress")', function() {
      // uncomment below and update the code to test the property useraddress
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

    it('should have the property usertax (base name: "usertax")', function() {
      // uncomment below and update the code to test the property usertax
      //var instance = new TempApi.User();
      //expect(instance).to.be();
    });

  });

}));
